// packages/openbridge-webcomponents-vue/src/components/notification-message-item/NotificationMessageItem.vue

    <script setup lang="ts">
      import { h, useSlots, reactive } from "vue";
      import { assignSlotNodes, Slots } from "@lit-labs/vue-utils/wrapper-utils.js";
      import 'openbridge-webcomponents/dist/components/notification-message-item/notification-message-item.js';
      

      export interface Props {
     time?: string
   }

      const vueProps = defineProps<Props>();

      const defaults = reactive({} as Props);
      const vDefaults = {
        created(el: any) {
          for (const p in vueProps) {
            defaults[p as keyof Props] = el[p];
          }
        }
      };

      let hasRendered = false;

      

      const slots = useSlots();

      const render = () => {
        const eventProps = {
    
  };

        const props = eventProps as (typeof eventProps & Props);
        for (const p in vueProps) {
          const v = vueProps[p as keyof Props];
          if ((v !== undefined) || hasRendered) {
            (props[p as keyof Props] as unknown) = v ?? defaults[p as keyof Props];
          }
        }

        hasRendered = true;

        return h(
          'obc-notification-message-item',
          props,
          assignSlotNodes(slots as Slots)
        );
      };
    </script>
    <template><render v-defaults /></template>

// packages/openbridge-webcomponents-react/src/components/notification-message-item/notification-message-item.ts

 import * as React from 'react';
 import {createComponent} from '@lit/react';
 
 import {ObcNotificationMessageItem as ObcNotificationMessageItemElement} from '@tibnor/openbridge-webcomponents/dist/components/notification-message-item/notification-message-item.js';
 
 
 

 
 export const ObcNotificationMessageItem = createComponent({
   react: React,
   tagName: 'obc-notification-message-item',
   elementClass: ObcNotificationMessageItemElement,
   events: {
     
   }
  });
