// packages/openbridge-webcomponents-ng/src/components/divider/divider.ts
import {
  Component,
  ElementRef,
  NgZone

} from '@angular/core';


import type {ObcDivider as ObcDividerElement} from '@ocean-industries-concept-lab/openbridge-webcomponents/dist/components/divider/divider.js';
import '@ocean-industries-concept-lab/openbridge-webcomponents/dist/components/divider/divider.js';

@Component({
  selector: 'obc-divider',
  template: '<ng-content></ng-content>',
})
export class ObcDivider {
  
  

  constructor(
    _e: ElementRef<ObcDividerElement>,
    _ngZone: NgZone
  ) {
    
    
    
  }

  

  
}

// packages/openbridge-webcomponents-react/src/components/divider/divider.ts

 import * as React from 'react';
 import {createComponent} from '@lit/react';
 
 import {ObcDivider as ObcDividerElement} from '@ocean-industries-concept-lab/openbridge-webcomponents/dist/components/divider/divider.js';
 
 
 

 
 export const ObcDivider = createComponent({
   react: React,
   tagName: 'obc-divider',
   elementClass: ObcDividerElement,
   events: {
     
   }
  });
