// packages/openbridge-webcomponents-react/src/components/divider/divider.ts

 import * as React from 'react';
 import {createComponent} from '@lit/react';
 
 import {ObcDivider as ObcDividerElement} from '@oicl/openbridge-webcomponents/dist/components/divider/divider.js';
 
 
 

 
 export const ObcDivider = createComponent({
   react: React,
   tagName: 'obc-divider',
   elementClass: ObcDividerElement,
   events: {
     
   }
  });

// packages/openbridge-webcomponents-vue/src/components/divider/Divider.vue

    <script setup lang="ts">
      import { h, useSlots } from "vue";
      import { assignSlotNodes, Slots } from "@lit-labs/vue-utils/wrapper-utils.js";
      import 'openbridge-webcomponents/dist/components/divider/divider.js';

      

      const slots = useSlots();

      const render = () => {
        const eventProps = {
    
  };

        const props = eventProps as (typeof eventProps);

        return h(
          'obc-divider',
          props,
          assignSlotNodes(slots as Slots)
        );
      };
    </script>
    <template><render v-defaults /></template>
