// packages/openbridge-webcomponents-vue/src/components/app-menu/AppMenu.vue

    <script setup lang="ts">
      import { h, useSlots } from "vue";
      import { assignSlotNodes, Slots } from "@lit-labs/vue-utils/wrapper-utils.js";
      import 'openbridge-webcomponents/dist/components/app-menu/app-menu.js';
      

      export interface Props {
     
   }
      

      const slots = useSlots();

      const render = () => {
        const eventProps = {
    
  };

        const props = eventProps as (typeof eventProps & Props);

        return h(
          'obc-app-menu',
          props,
          assignSlotNodes(slots as Slots)
        );
      };
    </script>
    <template><render v-defaults /></template>

// packages/openbridge-webcomponents-react/src/components/app-menu/app-menu.ts

 import * as React from 'react';
 import {createComponent} from '@lit/react';
 
 import {ObcAppMenu as ObcAppMenuElement} from '@oicl/openbridge-webcomponents/dist/components/app-menu/app-menu.js';
 
 
 

 
 export const ObcAppMenu = createComponent({
   react: React,
   tagName: 'obc-app-menu',
   elementClass: ObcAppMenuElement,
   events: {
     
   }
  });
