// packages/openbridge-webcomponents-ng/src/components/notification-message/notification-message.ts
import {
  Component,
  ElementRef,
  NgZone,
  Input

} from '@angular/core';


import type {ObcNotificationMessage as ObcNotificationMessageElement} from '@ocean-industries-concept-lab/openbridge-webcomponents/dist/components/notification-message/notification-message.js';
import '@ocean-industries-concept-lab/openbridge-webcomponents/dist/components/notification-message/notification-message.js';

@Component({
  selector: 'obc-notification-message',
  template: '<ng-content></ng-content>',
})
export class ObcNotificationMessage {
  private _el: ObcNotificationMessageElement;
  private _ngZone: NgZone;

  constructor(
    e: ElementRef<ObcNotificationMessageElement>,
    ngZone: NgZone
  ) {
    this._el = e.nativeElement;
    this._ngZone = ngZone;
    
  }

  
  @Input()
  set large(v: boolean) {
    this._ngZone.runOutsideAngular(() => (this._el.large = v));
  }

  get large() {
    return this._el.large;
  }
  
  @Input()
  set empty(v: boolean) {
    this._ngZone.runOutsideAngular(() => (this._el.empty = v));
  }

  get empty() {
    return this._el.empty;
  }
  

  
}

// packages/openbridge-webcomponents-react/src/components/notification-message/notification-message.ts

 import * as React from 'react';
 import {createComponent} from '@lit/react';
 
 import {ObcNotificationMessage as ObcNotificationMessageElement} from '@ocean-industries-concept-lab/openbridge-webcomponents/dist/components/notification-message/notification-message.js';
 
 
 

 
 export const ObcNotificationMessage = createComponent({
   react: React,
   tagName: 'obc-notification-message',
   elementClass: ObcNotificationMessageElement,
   events: {
     
   }
  });
