// packages/openbridge-webcomponents-vue/src/components/alert-menu/AlertMenu.vue

    <script setup lang="ts">
      import { h, useSlots, reactive } from "vue";
      import { assignSlotNodes, Slots } from "@lit-labs/vue-utils/wrapper-utils.js";
      import 'openbridge-webcomponents/dist/components/alert-menu/alert-menu.js';
      

      export interface Props {
     narrow?: boolean
   }

      const vueProps = defineProps<Props>();

      const defaults = reactive({} as Props);
      const vDefaults = {
        created(el: any) {
          for (const p in vueProps) {
            defaults[p as keyof Props] = el[p];
          }
        }
      };

      let hasRendered = false;

      const emit = defineEmits<{
        (e: 'ack-all-click', payload: CustomEvent<unknown>): void
      }>();

      const slots = useSlots();

      const render = () => {
        const eventProps = {
    onAckAllClick: (event: CustomEvent<unknown>) => emit('ack-all-click', event as CustomEvent<unknown>)
  };

        const props = eventProps as (typeof eventProps & Props);
        for (const p in vueProps) {
          const v = vueProps[p as keyof Props];
          if ((v !== undefined) || hasRendered) {
            (props[p as keyof Props] as unknown) = v ?? defaults[p as keyof Props];
          }
        }

        hasRendered = true;

        return h(
          'obc-alert-menu',
          props,
          assignSlotNodes(slots as Slots)
        );
      };
    </script>
    <template><render v-defaults /></template>

// packages/openbridge-webcomponents-react/src/components/alert-menu/alert-menu.ts

 import * as React from 'react';
 import {createComponent, EventName} from '@lit/react';
 
 import {ObcAlertMenu as ObcAlertMenuElement} from '@oicl/openbridge-webcomponents/dist/components/alert-menu/alert-menu.js';
 
 
 

 
 export const ObcAlertMenu = createComponent({
   react: React,
   tagName: 'obc-alert-menu',
   elementClass: ObcAlertMenuElement,
   events: {
     
     onAckAllClick: 'ack-all-click' as EventName<CustomEvent<unknown>>,
     onAlertListClick: 'alert-list-click' as EventName<CustomEvent<unknown>>,
   }
  });
