// packages/openbridge-webcomponents-ng/src/components/alert-menu/alert-menu.ts
import {
  Component,
  ElementRef,
  NgZone,
  Input,
  EventEmitter,
  Output

} from '@angular/core';


import type {ObcAlertMenu as ObcAlertMenuElement} from '@ocean-industries-concept-lab/openbridge-webcomponents/dist/components/alert-menu/alert-menu.js';
import '@ocean-industries-concept-lab/openbridge-webcomponents/dist/components/alert-menu/alert-menu.js';

@Component({
  selector: 'obc-alert-menu',
  template: '<ng-content></ng-content>',
})
export class ObcAlertMenu {
  private _el: ObcAlertMenuElement;
  private _ngZone: NgZone;

  constructor(
    e: ElementRef<ObcAlertMenuElement>,
    ngZone: NgZone
  ) {
    this._el = e.nativeElement;
    this._ngZone = ngZone;
    
    this._el.addEventListener('ack-all-click', (e: Event) => {
      // TODO(justinfagnani): we need to let the element say how to get a value
      // from an event, ex: e.value
      this.ackAllClickEvent.emit(e);
    });
    
    this._el.addEventListener('alert-list-click', (e: Event) => {
      // TODO(justinfagnani): we need to let the element say how to get a value
      // from an event, ex: e.value
      this.alertListClickEvent.emit(e);
    });
    
  }

  
  @Input()
  set empty(v: boolean) {
    this._ngZone.runOutsideAngular(() => (this._el.empty = v));
  }

  get empty() {
    return this._el.empty;
  }
  

  
  @Output()
  ackAllClickEvent = new EventEmitter<unknown>();
  
  @Output()
  alertListClickEvent = new EventEmitter<unknown>();
  
}

// packages/openbridge-webcomponents-react/src/components/alert-menu/alert-menu.ts

 import * as React from 'react';
 import {createComponent, EventName} from '@lit/react';
 
 import {ObcAlertMenu as ObcAlertMenuElement} from '@Ocean-Industries-Concept-Lab/openbridge-webcomponents/dist/components/alert-menu/alert-menu.js';
 
 
 

 
 export const ObcAlertMenu = createComponent({
   react: React,
   tagName: 'obc-alert-menu',
   elementClass: ObcAlertMenuElement,
   events: {
     
     onAckAllClick: 'ack-all-click' as EventName<CustomEvent<unknown>>,
     onAlertListClick: 'alert-list-click' as EventName<CustomEvent<unknown>>,
   }
  });
