// packages/openbridge-webcomponents-vue/src/components/navigation-menu/NavigationMenu.vue

    <script setup lang="ts">
      import { h, useSlots } from "vue";
      import { assignSlotNodes, Slots } from "@lit-labs/vue-utils/wrapper-utils.js";
      import 'openbridge-webcomponents/dist/components/navigation-menu/navigation-menu.js';
      


      const slots = useSlots();

      const render = () => {
        const eventProps = {
    
  };

        const props = eventProps as (typeof eventProps);

        return h(
          'obc-navigation-menu',
          props,
          assignSlotNodes(slots as Slots)
        );
      };
    </script>
    <template><render v-defaults /></template>

// packages/openbridge-webcomponents-react/src/components/navigation-menu/navigation-menu.ts

 import * as React from 'react';
 import {createComponent} from '@lit/react';
 
 import {ObcNavigationMenu as ObcNavigationMenuElement} from '@oicl/openbridge-webcomponents/dist/components/navigation-menu/navigation-menu.js';
 
 
 

 
 export const ObcNavigationMenu = createComponent({
   react: React,
   tagName: 'obc-navigation-menu',
   elementClass: ObcNavigationMenuElement,
   events: {
     
   }
  });
