// packages/openbridge-webcomponents-ng/src/components/navigation-menu/navigation-menu.ts
import {
  Component,
  ElementRef,
  NgZone

} from '@angular/core';


import type {ObcNavigationMenu as ObcNavigationMenuElement} from '@ocean-industries-concept-lab/openbridge-webcomponents/dist/components/navigation-menu/navigation-menu.js';
import '@ocean-industries-concept-lab/openbridge-webcomponents/dist/components/navigation-menu/navigation-menu.js';

@Component({
  selector: 'obc-navigation-menu',
  template: '<ng-content></ng-content>',
})
export class ObcNavigationMenu {
  
  

  constructor(
    _e: ElementRef<ObcNavigationMenuElement>,
    _ngZone: NgZone
  ) {
    
    
    
  }

  

  
}

// packages/openbridge-webcomponents-react/src/components/navigation-menu/navigation-menu.ts

 import * as React from 'react';
 import {createComponent} from '@lit/react';
 
 import {ObcNavigationMenu as ObcNavigationMenuElement} from '@Ocean-Industries-Concept-Lab/openbridge-webcomponents/dist/components/navigation-menu/navigation-menu.js';
 
 
 

 
 export const ObcNavigationMenu = createComponent({
   react: React,
   tagName: 'obc-navigation-menu',
   elementClass: ObcNavigationMenuElement,
   events: {
     
   }
  });
