// packages/openbridge-webcomponents-vue/src/components/alert-menu-item/AlertMenuItem.vue

    <script setup lang="ts">
      import { h, useSlots, reactive } from "vue";
      import { assignSlotNodes, Slots } from "@lit-labs/vue-utils/wrapper-utils.js";
      import 'openbridge-webcomponents/dist/components/alert-menu-item/alert-menu-item.js';
      

      export interface Props {
     message?: string;
     time?: string;
     timeSince?: string;
     acknowledgeble?: boolean;
     acknowledged?: boolean;
     narrow?: boolean
   }

      const vueProps = defineProps<Props>();

      const defaults = reactive({} as Props);
      const vDefaults = {
        created(el: any) {
          for (const p in vueProps) {
            defaults[p as keyof Props] = el[p];
          }
        }
      };

      let hasRendered = false;

      const emit = defineEmits<{
        (e: 'ack-click', payload: CustomEvent<unknown>): void
      }>();

      const slots = useSlots();

      const render = () => {
        const eventProps = {
    onAckClick: (event: CustomEvent<unknown>) => emit('ack-click', event as CustomEvent<unknown>)
  };

        const props = eventProps as (typeof eventProps & Props);
        for (const p in vueProps) {
          const v = vueProps[p as keyof Props];
          if ((v !== undefined) || hasRendered) {
            (props[p as keyof Props] as unknown) = v ?? defaults[p as keyof Props];
          }
        }

        hasRendered = true;

        return h(
          'obc-alert-menu-item',
          props,
          assignSlotNodes(slots as Slots)
        );
      };
    </script>
    <template><render v-defaults /></template>

// packages/openbridge-webcomponents-react/src/components/alert-menu-item/alert-menu-item.ts

 import * as React from 'react';
 import {createComponent, EventName} from '@lit/react';
 
 import {ObcAlertMenuItem as ObcAlertMenuItemElement} from '@tibnor/openbridge-webcomponents/dist/components/alert-menu-item/alert-menu-item.js';
 
 
 

 
 export const ObcAlertMenuItem = createComponent({
   react: React,
   tagName: 'obc-alert-menu-item',
   elementClass: ObcAlertMenuItemElement,
   events: {
     
     onAckClick: 'ack-click' as EventName<CustomEvent<unknown>>,
   }
  });
