// packages/openbridge-webcomponents-react/src/components/app-menu/app-menu.ts

 import * as React from 'react';
 import {createComponent} from '@lit/react';
 
 import {ObcAppMenu as ObcAppMenuElement} from '@ocean-industries-concept-lab/openbridge-webcomponents/dist/components/app-menu/app-menu.js';
 
 
 

 
 export const ObcAppMenu = createComponent({
   react: React,
   tagName: 'obc-app-menu',
   elementClass: ObcAppMenuElement,
   events: {
     
   }
  });

// packages/openbridge-webcomponents-ng/src/components/app-menu/app-menu.ts
import {
  Component,
  ElementRef,
  NgZone

} from '@angular/core';


import type {ObcAppMenu as ObcAppMenuElement} from '@ocean-industries-concept-lab/openbridge-webcomponents/dist/components/app-menu/app-menu.js';
import '@ocean-industries-concept-lab/openbridge-webcomponents/dist/components/app-menu/app-menu.js';

@Component({
  selector: 'obc-app-menu',
  template: '<ng-content></ng-content>',
})
export class ObcAppMenu {
  
  

  constructor(
    _e: ElementRef<ObcAppMenuElement>,
    _ngZone: NgZone
  ) {
    
    
    
  }

  

  
}
