// packages/openbridge-webcomponents-ng/src/components/breadcrumb/breadcrumb.ts
import {
  Component,
  ElementRef,
  NgZone,
  Input

} from '@angular/core';
import {BreadcrumbItem} from '@ocean-industries-concept-lab/openbridge-webcomponents/dist/components/breadcrumb/breadcrumb.js';
export type {BreadcrumbItem} from '@ocean-industries-concept-lab/openbridge-webcomponents/dist/components/breadcrumb/breadcrumb.js';
import type {ObcBreadcrumb as ObcBreadcrumbElement} from '@ocean-industries-concept-lab/openbridge-webcomponents/dist/components/breadcrumb/breadcrumb.js';
import '@ocean-industries-concept-lab/openbridge-webcomponents/dist/components/breadcrumb/breadcrumb.js';

@Component({
  selector: 'obc-breadcrumb',
  template: '<ng-content></ng-content>',
})
export class ObcBreadcrumb {
  private _el: ObcBreadcrumbElement;
  private _ngZone: NgZone;

  constructor(
    e: ElementRef<ObcBreadcrumbElement>,
    ngZone: NgZone
  ) {
    this._el = e.nativeElement;
    this._ngZone = ngZone;
    
  }

  
  @Input()
  set items(v: BreadcrumbItem[]) {
    this._ngZone.runOutsideAngular(() => (this._el.items = v));
  }

  get items() {
    return this._el.items;
  }
  

  
}

// packages/openbridge-webcomponents-react/src/components/breadcrumb/breadcrumb.ts

 import * as React from 'react';
 import {createComponent} from '@lit/react';
 
 import {ObcBreadcrumb as ObcBreadcrumbElement} from '@Ocean-Industries-Concept-Lab/openbridge-webcomponents/dist/components/breadcrumb/breadcrumb.js';
 
 
 

 
 export const ObcBreadcrumb = createComponent({
   react: React,
   tagName: 'obc-breadcrumb',
   elementClass: ObcBreadcrumbElement,
   events: {
     
   }
  });
